baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "The Vegasian"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Recipes"
    url     = "portfolio"
    weight  = 3
    [[menu.nav]]
    name    = "Culinary Adventures"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Topic"
    placeholder_about_the_project = "Message"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "Recipes"
      title  = "Recipes"
    [[params.contactForm.projectType]]
      value = "Culinary Adventures"
      title  = "Culinary Adventures"
    [[params.contactForm.projectType]]
      value = "Products"
      title  = "Products"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/IMG_1467.jpg"
    heading               = "Your Vegan Asian Buddy"
    tagline               = "HI THERE! IT'S HA HERE :)"
    primary_button        = "Straight to The Recipes"
    primary_button_url    = "portfolio"
    secondary_button      = "Join Culinary Adventures"
    secondary_button_url  = "blog"

  [params.portfolio]
    enable    = true
    title     = "NEWEST RECIPES"
    url = "portfolio"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET'S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"


  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Address"
      address = "Pelikaanstraat 54<br>1221KN, Hilversum"
      phone   = "(+31) 6 203 321 89"
      email   = "ha.thevegasian@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Recipes"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Culinary Adventures"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media Channels
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/ha.thevegasian/"
        [[params.footer.social.link]]
          name = "YouTube"
          url  = "https://www.youtube.com/@thevegasian"
        [[params.footer.social.link]]
          name = "TikTok"
          url  = "https://www.tiktok.com/@thevegasian?_t=8eaLyEEebwX&_r=1"
      # Footer Service
      [params.footer.service]
        title       = ""
        description = ""